filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/dev/error/authentication/authentication-exception.log
      - /app/logs/dev/error/authorization/authorization-exception.log
      - /app/logs/dev/error/admin/admin-login-fail.log
      - /app/logs/dev/error/service/error-service-exception.log
      - /app/logs/dev/error/request/error-request-exception.log
      - /app/logs/dev/warn/service/warn-service-exception.log
      - /app/logs/dev/warn/request/warn-request-exception.log
      - /app/logs/dev/info/search/search.log
      - /app/logs/dev/info/admin/admin-auth.log
      - /app/logs/dev/info/http/http-transaction.log
      - /app/logs/dev/info/view/post-view.log

      - /app/logs/prod/error/authentication/authentication-exception.log
      - /app/logs/prod/error/authorization/authorization-exception.log
      - /app/logs/prod/error/admin/admin-login-fail.log
      - /app/logs/prod/error/service/error-service-exception.log
      - /app/logs/prod/error/request/error-request-exception.log
      - /app/logs/prod/warn/service/warn-service-exception.log
      - /app/logs/prod/warn/request/warn-request-exception.log
      - /app/logs/prod/info/search/search.log
      - /app/logs/prod/info/admin/admin-auth.log
      - /app/logs/prod/info/http/http-transaction.log
      - /app/logs/prod/info/view/post-view.log
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
