input {
  beats {
    port => 5044
  }
}

filter {
  # 경로에서 environment, log_type 추출
  dissect {
      mapping => {
        "[log][file][path]" => "/app/logs/%{environment}/%{level}/%{log_type}/%{log_filename}"
      }
    }

  mutate {
    gsub => ["log_filename", "\.log$", ""]
  }

  # @timestamp를 한국 시간(KST, UTC+9)으로 조정
  date {
    match => ["@timestamp", "ISO8601"]
    timezone => "Asia/Seoul"
  }
  # json message 필드 파싱
  if [message] {
    json {
      source => "message"
      target => "parsed_json"
      skip_on_invalid_json => true
    }

    if [parsed_json] {
      ruby {
        code => "
          parsed = event.get('parsed_json')
          if parsed.is_a?(Hash)
            parsed.each do |k, v|
              event.set(k, v)
            end
          end
          event.remove('parsed_json')
        "
      }
    }
  }
  # environment 필드 추가
  if [environment] == "dev" {
    mutate {
      add_tag => ["development"]
      add_field => { "env" => "dev" }
    }
  } else if [environment] == "prod" {
    mutate {
      add_tag => ["production"]
      add_field => { "env" => "prod" }
    }
  }

  # level 태그 추가
  if [level] == "error" {
    mutate { add_tag => ["error"] }
  } else if [level] == "warn" {
    mutate { add_tag => ["warning"] }
  } else if [level] == "info" {
    mutate { add_tag => ["info"] }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[environment]}-%{[log_filename]}-%{+YYYY.MM.dd}"
  }
}
