spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-client-secret
            redirect-uri: http://localhost:8080/api/v1/users/google/login/google/callback

jwt:
  secret:
    key: dGVzdC1zZWNyZXQta2V5
  expiration:
    time: 60000
  refresh-token:
    expiration-time: 7200000

aes:
  secret:
    key: dGVzdC1hdXRoLWtleQ==
