app:
  cookie:
    secure: true
    sameSite: None
    domain:
    frontend-origin: https://www.ndgl.shop

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: redis_1
      port: 6379

    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: http://localhost:9200
    ssl:
      verification-mode: none

elasticsearch:
  port: 9200
  enabled: false

logging:
  level:
    com.ndgl.spotfinder: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO