app:
  cookie:
    secure: false
    sameSite: Lax
    domain: localhost
    frontend-origin: http://localhost:3000

server:
  port: 8080

spring:
  config:
    import:
      optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_GOOGLE_CLIENT_ID}
            client_secret: ${SPRING_SECURITY_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${SPRING_SECURITY_GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: email
            client-name: Google
            provider: google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            #user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: sub
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    aws:
      s3:
        bucket: ${AWS_BUCKET_NAME}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
        
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

  expiration:
    time: ${JWT_VALIDATION_TIME}

  refresh-token:
    expiration-time: ${JWT_REFRESH_VALIDATION_TIME}

  auth:
    key: ${AUTHORIZATION_KEY}

aes:
  secret:
    key: ${AES_SECRET_KEY}

auth:
  header:
    prefix: Bearer

springdoc:
  default-produces-media-type: application/json;charset=UTF-8

logging:
  level:
    com.ndgl.spotfinder: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE